# Project: Maggiore3
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"//SERVERNAS/massimo.sandretti$/Anno scolastico 2018-2019/Infomatica/C++/Compilatori/File/Dev-Cpp592 Portable GRAPH CONIO2/MinGW64/lib32" -L"//SERVERNAS/massimo.sandretti$/Anno scolastico 2018-2019/Infomatica/C++/Compilatori/File/Dev-Cpp592 Portable GRAPH CONIO2/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"//SERVERNAS/massimo.sandretti$/Anno scolastico 2018-2019/Infomatica/C++/Compilatori/File/Dev-Cpp592 Portable GRAPH CONIO2/MinGW64/include" -I"//SERVERNAS/massimo.sandretti$/Anno scolastico 2018-2019/Infomatica/C++/Compilatori/File/Dev-Cpp592 Portable GRAPH CONIO2/MinGW64/x86_64-w64-mingw32/include" -I"//SERVERNAS/massimo.sandretti$/Anno scolastico 2018-2019/Infomatica/C++/Compilatori/File/Dev-Cpp592 Portable GRAPH CONIO2/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"//SERVERNAS/massimo.sandretti$/Anno scolastico 2018-2019/Infomatica/C++/Compilatori/File/Dev-Cpp592 Portable GRAPH CONIO2/MinGW64/include" -I"//SERVERNAS/massimo.sandretti$/Anno scolastico 2018-2019/Infomatica/C++/Compilatori/File/Dev-Cpp592 Portable GRAPH CONIO2/MinGW64/x86_64-w64-mingw32/include" -I"//SERVERNAS/massimo.sandretti$/Anno scolastico 2018-2019/Infomatica/C++/Compilatori/File/Dev-Cpp592 Portable GRAPH CONIO2/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"//SERVERNAS/massimo.sandretti$/Anno scolastico 2018-2019/Infomatica/C++/Compilatori/File/Dev-Cpp592 Portable GRAPH CONIO2/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Maggiore3.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
