[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=ExtractOnly
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=I
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=Grazie! i file di "Test Di Battitura" sono stati estratti con successo!
TargetName=C:\Users\Massimo Sandretti\Desktop\TEST DI BATTITURA INSTALLER\Test Di Battitura.EXE
FriendlyName=Test Di Battitura
AppLaunched=
PostInstallCmd=
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="input.txt"
FILE1="leggimi.txt"
FILE2="TestDiBattitura.exe"
FILE3="wordHandler.exe"
FILE4="words.txt"
[SourceFiles]
SourceFiles0=C:\Users\Massimo Sandretti\Desktop\test di battitura\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
%FILE3%=
%FILE4%=
